name: GitHub Pages Build

on:
  push:
    branches:
      - main # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - ðŸ›Žï¸ Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
          lfs: true # Fetch large files

      - name: Turn off LFS
        run: >-
          git lfs uninstall;
          rm -Rf .git;
          rm .gitattributes;

      - name: ðŸš€ Deploy to `gh-pages` branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: ./ # The folder the action should deploy.
          branch: gh-pages # The branch the action should deploy to.
          git-config-name: "github-actions[bot]"
          git-config-email: "github-actions[bot]@users.noreply.github.com"
          commit-message: "ðŸš€ Deployed using `JamesIves/github-pages-deploy-action"
